[2023-12-25 21:03:54,787] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset manual__2023-12-25T21:03:46.355583+00:00 [queued]>
[2023-12-25 21:03:54,793] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset manual__2023-12-25T21:03:46.355583+00:00 [queued]>
[2023-12-25 21:03:54,793] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-25 21:03:54,793] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-12-25 21:03:54,793] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-25 21:03:54,802] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): pivot_dataset> on 2023-12-25 21:03:46.355583+00:00
[2023-12-25 21:03:54,805] {standard_task_runner.py:52} INFO - Started process 40101 to run task
[2023-12-25 21:03:54,808] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'titanic_pivot', 'pivot_dataset', 'manual__2023-12-25T21:03:46.355583+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/titanic_dag.py', '--cfg-path', '/tmp/tmp45hgobz4', '--error-file', '/tmp/tmpxuf3oxca']
[2023-12-25 21:03:54,809] {standard_task_runner.py:80} INFO - Job 24: Subtask pivot_dataset
[2023-12-25 21:03:54,862] {task_command.py:369} INFO - Running <TaskInstance: titanic_pivot.pivot_dataset manual__2023-12-25T21:03:46.355583+00:00 [running]> on host c975c50309df
[2023-12-25 21:03:54,927] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=titanic_pivot
AIRFLOW_CTX_TASK_ID=pivot_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-12-25T21:03:46.355583+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-25T21:03:46.355583+00:00
[2023-12-25 21:03:54,982] {python.py:173} INFO - Done. Returned value was: None
[2023-12-25 21:03:54,997] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=titanic_pivot, task_id=pivot_dataset, execution_date=20231225T210346, start_date=20231225T210354, end_date=20231225T210354
[2023-12-25 21:03:55,021] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-25 21:03:55,055] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
